<?php $this->headTitle($this->translate('Edit message')); ?>
<h1><?php echo $this->translate('Edit message'); ?></h1>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<div class="secnav">
    <a href="<?php echo $this->url('sms-msg', array('action'=>'index'));?>">
        <span class='back icon'><</span><?php echo $this->translate('back');?>
    </a>
</div>
<div class="mainform">
<?php 
$this->form->prepare();
echo $this->form()->openTag($this->form);

echo $this->formRow($this->form->get('Msg')->get('id'));
echo $this->formRow($this->form->get('Msg')->get('title'));
echo $this->formLabel($this->form->get('Msg')->get('text'));
echo $this->formTextarea($this->form->get('Msg')->get('text'));
echo $this->formElementErrors($this->form->get('Msg')->get('text'));
?>
        <p class="desc left"><?php echo $this->translate('Symbols:'); ?> 
            <span class="symbols">0</span>
        </p>
        <p class="desc right"><?php echo $this->translate('Messages:'); ?> 
            <span class="smss">0</span>
        </p>
<?php 
echo $this->formRow($this->form->get('submit'));

echo $this->form()->closeTag($this->form);

?>
</div>